### ISSUE TITLE
Module "immutable-assign" has no default export.

### ISSUE THREAD

**Issue by husainshabbir** [engineforce/ImmutableAssign#10]
I am using ImmutableAssign along with TypeScript on a project and import it using this:

    import iassign from "immutable-assign"

However, the above gives me this linting error: `error TS1192: Module '"immutable-assign"' has no default export.` Is this something that you can fix?

**Comment by martinbu** [comment]
I have the same problem within an Angular 4 Project using Angular Cli.

**Comment by engineforce** [comment]
Please try following:
```
import * as iassign from "immutable-assign"
```

**Comment by husainshabbir** [comment]
It does not work unfortunately. This way of importing does not invoke the iassign function at all.

**Comment by engineforce** [comment]
Please try 1.0.34, which is the new release, and still use following:

```
import * as iassign from "immutable-assign"
iassign(state, (s) => { ... });
```

**Comment by martinbu** [comment]
This works for me, thank you for the fast patch.
