### ISSUE TITLE
iassign does not work correctly with ES6 Map

### ISSUE THREAD

**Issue by martinbu** [engineforce/ImmutableAssign#12]
Hi, thanks for this great helper library.

Does this library support ES6 Map? For me the following example does not work correctly. 'm' is always empty in the setProp and therefore map3 (or mapX) contains always one element after adding further elements.

```ts
import * as iassign from 'immutable-assign';

iassign.setOption({useConstructor: true});

let map1 = new Map();

  let map2 = iassign(
    map1,
    m => {
      m.set(0, 'first'); return m;
    }
  );

  let map3 = iassign(
    map2,
    m => { m.set(1, 'second'); return m; }
  );

  console.log(map1.size) // size: 0
  console.log(map2.size) // size: 1
  console.log(map3.size) // size: 1

````

Additionally, I have to set the useConstructor Option in every file (after import), that the option is applied correctly.

**Comment by engineforce** [comment]
ES6 Map support is added in 1.0.36, please refer to [example 9](https://github.com/engineforce/ImmutableAssign#example-9-support-es6-map)

**Comment by engineforce** [comment]
Regarding to set the useConstructor Option in every file (after import), can you create a git repo that can reproduce the bug?
