### ISSUE TITLE
Return the existing object when the value being set hasn't changed

### ISSUE THREAD

**Issue by bjoyx** [engineforce/ImmutableAssign#14]
const v1 = {message: "hello", recipient: {name: "world"}}

    const v2 = immutableAssign(message, m => m.name, name => "world")

    assert.strictEqual(v1, v2) // currently fails

**Comment by engineforce** [comment]
You can use the *ignoreIfNoChange* option, please pay attention to [Error when freeze and ignoreIfNoChange both true](https://github.com/engineforce/ImmutableAssign/issues/11)
