### ISSUE TITLE
Add a function to only freeze (if enabled)

### ISSUE THREAD

**Issue by geirsagberg** [engineforce/ImmutableAssign#16]
When using `seamless-immutable`, I usually do `Immutable.from(result)` for all my AJAX-calls, so I am sure it will not be changed further down the line.

It would be nice to have a similar function for ImmutableAssign, that would `Object.Freeze` if enabled, otherwise it would do nothing.

Example:

`const immutableResult = iassign(result)`

**Comment by JiriZidek** [comment]
Feel free to use DeepFreeze instead...

**Comment by geirsagberg** [comment]
I did something like this:

```
import iassign from 'sea'
import DeepFreeze from 'deep-freeze'

export const deepFreeze = obj => iassign.freeze ? DeepFreeze(obj) : obj
```
Would you be opposed to a PR with such a wrapper included in ImmutableAssign?

**Comment by JiriZidek** [comment]
Why create dependency on DeepFreeze, when benefit (freezing is usefull for developer only, in production it is no-no) is so small ? Moreover you can add such trival wrapper to your project as single function without forcing all consumers of iassign to bloat their code with DeepFreeze?

**Comment by JiriZidek** [comment]
Now I see that DeepFreeze is in current version required anyway...

**Comment by engineforce** [comment]
Hi geirsagberg, I am not a fan of re-exporting of another module, which is antipattern. The better way is that you create your own module (called immutable-util for example), which export iassign() and deepFreeze(). And make your application codes depending on the new module, so you can swap out iassign() in the future if needed.

**Comment by geirsagberg** [comment]
That's good advice, I might just do that. Thanks!
