### ISSUE TITLE
How to handle possibly null values in getProp?

### ISSUE THREAD

**Issue by epeli** [engineforce/ImmutableAssign#17]
I'm using `strictNullChecks` in my project. It seems that the `getProp` function does not allow if-statements in the function body. There for I'm getting `Error: getProp() function has statements other than 'return'` errors. 

Is there a way to workaround this?

Here's an example which produces this error:

```js
  import i from "immutable-assign";

  interface IState {
      foo?: {
          bar?: number;
      };
  }

  const state: IState = {};

  // Does not compile
  //     foo.tsx (12,32): Object is possibly 'undefined'. (2532)
  // const newState = i(state, s => s.foo.bar, () => 1);

  // Throws at runtime with 
  //     Error: getProp() function has statements other than 'return': const foo = s.foo;
  const newState = i(
      state,
      s => {
          const foo = s.foo;
          if (foo) {
              return foo.bar;
          }

          return null;
      },
      () => 1,
  );
```

**Comment by JiriZidek** [comment]
IMHO I think that your "if" logic should go to "setter" function. Getter is just "semantical description of path", it is not real imperative code... hence no imperative "if".

**Comment by epeli** [comment]
Hmm. That makes the setter bit awkward depending on the case.  I think #15 would solve this nicely?

**Comment by shroo-paulli** [comment]
Interesting use case, I don't think #15 (proxy) would work for your case. But feel free to try out that pull request, let me know if it works.

Another solution I can think of is using nested iassign.
```
const newState = i(
    state,
    s => s.foo,
    (foo) => {
        return i(foo || {}, (f) => f.bar, () => 1);
    },
);
```

**Comment by JiriZidek** [comment]
Maybe TS is smart enough to infer notnullability from this:
`if(state.foo) state = iassign(state, g=>g.foo.bar, s => 1);`
Otherwise ! might be used (or there is another syntax?).
`if(state.foo) state = iassign(state, g=>g!.foo.bar, s => 1);`

**Comment by engineforce** [comment]
Hi epeli,

Your use case should work now with 2.0.4, with some modification:

``` javascript
let newState = i(
    state,
    s => {
        const foo = s.foo;
        if (foo) {
            return foo.bar;
        }

        // must return the same value as the setProp() to prevent update.
        return 1;
    },
    () => 1,
    undefined,
    {
        ignoreIfNoChange: true,
    }
);
```
