### ISSUE TITLE
Proxy polyfill not applied on iOS 9.0 / Android 6.0

### ISSUE THREAD

**Issue by studyroz** [engineforce/ImmutableAssign#19]
I'm developing mobile app with React-Native + TypeScript. After upgrading iassign to 2.0.0, JS engine throws `Can't find variable: Proxy` error.

## Environment

ImmutableAssign - 2.0.0
React Native - 0.48.2
OS: iOS 9.0 / Android 6.0 ( iOS 10.0+ works fine )

**Comment by engineforce** [comment]
Not sure what happened, can you try to install and import [proxy-polyfill](https://github.com/GoogleChrome/proxy-polyfill) explicitly.

**Comment by StephenPaul** [comment]
After switching from 2.0.0 to 2.0.1 My webpack with Uglify plugin is throwing an error `Unexpected token: name (lastRevokeFn)`. Seems to be related to [this](https://github.com/webpack/webpack/issues/2972). Any ideas on a workaround?
