### ISSUE TITLE
typescript types for immutable-assign

### ISSUE THREAD

**Issue by st-clair-clarke** [engineforce/ImmutableAssign#20]
Hi, Are there any typing definition to use immutable-assign with typescript?

Thanks

**Comment by engineforce** [comment]
It is already in the immutable-assign npm package, next to the js file.

**Comment by st-clair-clarke** [comment]
Then why why does the import statement is starts with require instead of typescript import?

**Comment by shroo-paulli** [comment]
Do you mean my examples in the README.MD? Those examples are JavaScript examples, because this library can be used in both JavaScript and TypeScript projects.

**Comment by st-clair-clarke** [comment]
Hi,
I am using typescript with Webstorm

I try to use the following:// 2.1: Calling iassign() to push items to list1, using overload 2
```
      let list2 = iassign(
          list1,
          function (l) { l.push(3, 4, 5); return l; }
      );
```

When I click on iassign symbol Webstorm does the following import

`import iassign = require('immutable-assign')`

NOT the typescript form of import. I would think the typescript form should be imported since the typescrpt definition file is present.

Cheers

**Comment by shroo-paulli** [comment]
Please try:
`import * as iassign from "immutable-assign";`

**Comment by st-clair-clarke** [comment]
Thanks for your help. It now works.
