### ISSUE TITLE
Does not work with create-react-app

### ISSUE THREAD

**Issue by silentlight** [engineforce/ImmutableAssign#21]
Hi,

When I try to build my project using create-react-app I get an error: `Failed to minify the code from this file: ./node_modules/proxy-polyfill/proxy.js:24`. I see that some of the packages does not pre-compile to ES5. Here is more info about this: https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify.

Do you have any idea how can this problem be fixed?

**Comment by engineforce** [comment]
Hi silentlight,

I have released 2.0.3, which has replaced the proxy-polyfill with Object.defineProperty(). And it should have fixed your problem, can you please try it out?
