### ISSUE TITLE
Unexpected behaviour when console.log-ing or using lodash/fp/find

### ISSUE THREAD

**Issue by siassaj** [engineforce/ImmutableAssign#28]
I was getting very inconsistent results using lodash's  `lodash/fp/find` to locate the element that I'd like to replace. So after some testing, we reduce to the following ... situation.

I get the distinct impression that this may not be fixable?

```typescript
const nested1 = { a:{ b:{ c:[ {id: 3}, {id: 4}, {id: 5}], d: 1 } } };

    const nested2 = iassign(
      nested1,
      function (n) {
        console.log("BOOM")
        const f = n.a.b.c[1]
        console.log(f)
        console.log(f == n.a.b.c[1])
        return f
      },
      function (c1) { return { id: 12}; }
    );

    console.log(JSON.stringify(nested2, null, 2))
```
gives output:
```
      BOOM
      { id: 4 }
      true
      BOOM
      { id: 4 }
      false
      {
        "a": {
          "b": {
            "c": [
              {
                "id": 3
              },
              {
                "id": 4
              },
              {
                "id": 5
              }
            ],
            "d": 1
          }
        }
      }
```

Why is the getter function being executed twice?

**Comment by engineforce** [comment]
I am fixing one of the unnecessary calls to the getProp(), however for performance reason of some functionalities (may not applicable to you): 1. `ignoreIfNoChange` option, 2. when Proxy is not available, I have to call getProp() 2 twice, that is why this library requires the `getProp()` to be a pure function (mentioned in README.md)

I am more interested in your use case for `lodash/fp/find`, see if I can help to fix the issue.

**Comment by engineforce** [comment]
@siassaj May I close the issue?

**Comment by siassaj** [comment]
@engineforce Thanks for responding, I was caught up with client work. I'll investigate it & take a look.
