### ISSUE TITLE
Nicer API

### ISSUE THREAD

**Issue by crubier** [engineforce/ImmutableAssign#3]
Hi, thanks for the amazing helper.

When using this library in conjunction with lodash/fp, I found that the API would be much more powerful if the argument order was changed (iteratee first, data last), and if it was curried, in the spirit of [lodash-fp](https://github.com/lodash/lodash/wiki/FP-Guide).

I usually define a function called `mutate`  this way:

```javascript
const mutate = (getter,setter,context?) => (state) => iassign(state,getter,setter,context,{freeze:true})
```

The resulting function `mutate` is extremely helpful, as it allows to represent "mutations" in a declarative way. These mutations can then be applied to data. Here is an example of use:

```javascript
const reducer = (state = initialState, action) => {

    switch (action.type) {

    case "TICK":
        return mutate(
          state=>state.time,
          time=>time+1
        )(state)
        
        ...

```

**Comment by crubier** [comment]
It also allows to combine mutations using lodash/fp `flow`operator:

```javascript

flow(
    mutate(
        state=>state.time,
        time=>time+1
    ),
    mutate(
        state=>state.score,
        score=>score*2
    )
)

```

**Comment by engineforce** [comment]
Hi Vincent,

Thanks for the advice, however your mutate function already works great, what do you want me to change in my library?

**Comment by engineforce** [comment]
Hi Vincent,

I have released 1.0.27, it includes a new function iassign.fp(), which is in functional programming friendly style, moved obj to the last parameter and supports currying. Please refer to [example 8](https://github.com/engineforce/ImmutableAssign#example-8-update-nested-structures-using-iassignfp-and-currying)

**Comment by crubier** [comment]
Hi, thank you this is very nice. 

However there is only one thing that could be made better: The order of argument could be changed in order to make this more useful: In the curried form, the `options` should be the first argument and not the last.

Also, to match `lodash/fp`, and as a matter of usability, it would be nice if it was autocurried, which means that we can call the function with any number of arguments, and it would be curried accordingly.

This would allow to write things like that
```javascript
import iassign from "immutable-assign"
// We create our instance with no options
iassignFp = iassign.fp( undefined ) 

// ...

var nested1 = { a: { b: { c: [3, 4, 5] } } };

// ...

var mutation = iassignFp(
    (n, ctx) => (n.a.b.c[ctx.i])  ,
    (ci) => (ci + 100) ,
    {i: 1}
);

// ...

var nested2 = mutation(nested1);
```


I asked for this feature in your package, because otherwise I would have had to create a fork of your package just to implement this small change.

If you want I can code this and make a pull request. However you are really close right now

**Comment by engineforce** [comment]
Hi Vincent,

Regarding iassign.fp(), do you want me to reverse the parameter order completely, e.g.,

```javascript
iassign.fp = function <TObj, TProp, TContext>(    
    option: IIassignOption,
    context: TContext,
    setProp: setPropFunc<TProp>,
    getProp: getPropFunc<TObj, TProp, TContext>,
    obj: TObj): TObj; 
```

Or just move the **option** parameter to the first, e.g.,

```javascript
iassign.fp = function <TObj, TProp, TContext>(
    option: IIassignOption,
    getProp: getPropFunc<TObj, TProp, TContext>,
    setProp: setPropFunc<TProp>,
    context?: TContext,
    obj?: TObj): TObj; 
```

It does support auto currying already in 1.0.27, i.e., you can call the function with any number of arguments.

**Comment by crubier** [comment]
Hi, I just meant to move the `option` parameter first, **not** to reverse the argument order completely. 

Auto currying is excellent !

**Comment by engineforce** [comment]
Done in 1.0.28

**Comment by crubier** [comment]
Nice, perfect thank you a lot !
