### ISSUE TITLE
Provide initialization method

### ISSUE THREAD

**Issue by vincaslt** [engineforce/ImmutableAssign#7]
It would be nice to have a better way to initialize immutable object than:

```
const obj = iassign({
  prop: 'value'
}, (obj) => (obj))
```

Maybe make the setter function optional, and just initialize frozen object if it's not provided?

**Comment by JiriZidek** [comment]
IMHO I guess you don't need this. Freezing is for debug only. You can initialize your forst version of object normally:
let store = { prop: 'value' };
You would use iassign only when you need to change something:
strore = isassign(store, g=>g.prop, s=>'newval');

**Comment by engineforce** [comment]
I prefer not to change iassign to support the pure freeze operation, according to the single responsibility principle. You should import and use "deep-freeze" module for that purpose.
