### ISSUE TITLE
Cannot assign freeze property

### ISSUE THREAD

**Issue by vincaslt** [engineforce/ImmutableAssign#8]
Trying to write: `iassign.freeze = true` in vscode results in this error:
`[ts] Cannot assign to 'freeze' because it is a constant or a read-only property.`

This is because es6 imports are constants by default, so their properties are readonly.

**Comment by engineforce** [comment]
I will try to investigate; for now, you can work around the issue by importing immutable-assign using require() method.

**Comment by vincaslt** [comment]
Sure, I wrote a wrapper in my project that copies the object with the needed properties set, and some other extensions for now

**Comment by engineforce** [comment]
Fixed in 1.0.31, I have added setOption() function to update options.
